#!/usr/bin/env bash
set -e

echo ""
echo "=========================================="
echo "  VeeGo Driver App — Setup"
echo "=========================================="
echo ""

# ── 1. Check required secrets ──────────────────────────────────────────────
if [ -z "$BACKEND_URL" ]; then
  echo "❌  ERROR: BACKEND_URL secret is not set."
  echo "    Go to Replit Secrets and add BACKEND_URL with your backend server URL."
  echo ""
  exit 1
fi

echo "✅  BACKEND_URL found."

# ── 2. Write .env file ─────────────────────────────────────────────────────
echo ""
echo "📝  Writing .env file..."

cat > .env << EOF
# Auto-generated by setup.sh — do NOT edit manually.
# Source: BACKEND_URL Replit secret.
EXPO_PUBLIC_API_URL=${BACKEND_URL}
EOF

echo "✅  .env written:"
echo "    EXPO_PUBLIC_API_URL=${BACKEND_URL}"

# ── 3. Install dependencies ────────────────────────────────────────────────
echo ""
echo "📦  Installing dependencies..."
pnpm install --frozen-lockfile
echo "✅  Dependencies installed."

# ── 4. Kill any process on port 5000 ──────────────────────────────────────
echo ""
echo "🔍  Checking for processes on port 5000..."
PORT_PID=$(lsof -ti tcp:5000 2>/dev/null || true)
if [ -n "$PORT_PID" ]; then
  echo "    Killing PID(s): $PORT_PID"
  kill -9 $PORT_PID 2>/dev/null || true
  sleep 1
fi
echo "✅  Port 5000 is free."

# ── 5. Kill any stale Expo / Metro processes ───────────────────────────────
echo ""
echo "🔍  Checking for stale Expo / Metro processes..."
pkill -f "expo start" 2>/dev/null || true
pkill -f "metro"      2>/dev/null || true
sleep 1
echo "✅  Stale processes cleared."

# ── 6. Start Expo ─────────────────────────────────────────────────────────
echo ""
echo "🚀  Starting Expo (web + tunnel, port 5000, clear cache)..."
echo ""

exec CI=1 \
  EXPO_PACKAGER_PROXY_URL=https://$REPLIT_EXPO_DEV_DOMAIN \
  EXPO_PUBLIC_DOMAIN=$REPLIT_DEV_DOMAIN \
  EXPO_PUBLIC_REPL_ID=$REPL_ID \
  REACT_NATIVE_PACKAGER_HOSTNAME=$REPLIT_DEV_DOMAIN \
  pnpm exec expo start \
    --web \
    --tunnel \
    --clear \
    --port 5000
