kind = "mobile"
previewPath = "/"
title = "VeeGo Driver"
version = "1.0.0"
id = "artifacts/veego-driver"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 24067

[services.development]
run = "pnpm --filter @workspace/veego-driver run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/veego-driver", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/veego-driver", "run", "serve" ]

[services.env]
PORT = "24067"
BASE_PATH = "/"
